### PR TITLE
apply dependency fix

### PR DESCRIPTION
**Pull request by lalomartins**
as we discussed before — see https://github.com/brunch/brunch/issues/916 and https://github.com/stephenhutchings/jade-static-brunch/pull/1

up to you whether or not to apply while we discuss fixing that on the brunch level :smile_cat: but figured better to have the pull request around in case you decide you do want it.

### CODE REVIEW

**Comment by monokrome** [comment]
@lalomartins This is how jaded-brunch was doing this [in early 2013][old], but the feature for requesting brunch to skip storing the file was added to brunch afterward due to [an issue][iss] where I had a project that had a lot of static files which resulted in a large amount of unnecessary JavaScript in the output.


[iss]: https://github.com/brunch/brunch/issues/557

**Comment by es128** [comment]
The blunt answer is that Brunch was not designed to provide this capability, so all these solutions are inherently hacky workarounds with some drawbacks. I pointed out in brunch/brunch#916 where someone could look to tweak the workflow for a better fix, but it's not something I'm going to personally work on.

I have ideas for Brunch 2.0 which would make this a non-issue, but I don't honestly know when I'll work on that either.

**Comment by monokrome** [comment]
@es128 Maybe I'm missing something, but if it's an accepted enhancement in brunch then doesn't that imply that it's a use-case that is going to be supported? If it wasn't expected to work properly then I don't know why the enhancement would be accepted.

Either way, I'm asking because I want to dig in and see if I can fix it. That may not work, because brunch's code is not very helpful but I'm planning on giving it a shot if there's some expectation that there is going to be a release sometime soon.

I just don't want to spend time on it, submit a PR, and then a release never happens.

**Comment by es128** [comment]
A PR that solves the problem would be accepted and published

**Comment by es128** [comment]
I didn't mean in my earlier comment that the desired behavior here is being deliberately not supported. It just wasn't designed this way from the beginning, and as we've seen problems have arisen from trying to find ways to slide it in. There probably is an easy enough solution to the remaining problem, but at this point I think the better approach is to encourage community participation in figuring it out than waiting for me to personally focus on it.

**Comment by monokrome** [comment]
Thanks for clarifying, @es128. I'll attempt a fix sometime later this week :)

**Pull request closed without merging**
