### PR TITLE
Progeny hotfix.

### PR DESCRIPTION
**Pull request by monokrome**
Created in hopes to solve https://github.com/monokrome/jaded-brunch/issues/20

### CODE REVIEW

**Comment by samio80** [comment]
When are you planing to merge with the head?

**Comment by samio80** [comment]
yes :+1:

**Comment by monokrome** [comment]
@samio80 Great! I'm going to give this a test sometime today and then will merge and do a release tonight. Thanks so much for helping with this! :)

**Comment by samio80** [comment]
thats great thanks!!

**Comment by samio80** [comment]
@monokrome Can you please merge to the head?

**Comment by monokrome** [comment]
@samio80 This code fails for me locally... Did it work for you?

**Comment by monokrome** [comment]
@samio80 Looks like it's working! Thanks for the help on this one :)

**Pull request merged**
